version: "3"
# this file uses prebuilt image in dockerhub
services:
    jekyll:
        image: willem97/al-folio:v0.10.1
        # image: amirpourmand/al-folio:latest
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/srv/jekyll
